/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jgraphics;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.ListModel;
import javax.swing.Timer;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import jsolitaire.Board;
import jsolitaire.Board.Deck;
import jsolitaire.Card;
import jsolitaire.Move;

/**
 *
 * @author User
 */
public class GamePanel extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;

    private final int number;
    private int time = 0;
    private final Timer timer;
    private Boolean active = false;
    private final GameWindow parent;
    private jsolitaire.Board board = new Board();

    /**
     * Creates new form InternalBoard
     *
     * @param number
     * @param parent
     */
    public GamePanel(int number, GameWindow parent) {
        initComponents();

        this.number = number;
        this.parent = parent;

        ((BasicInternalFrameUI) super.getUI()).setNorthPane(null);

        newButton.setMnemonic(KeyEvent.VK_N);
        openButton.setMnemonic(KeyEvent.VK_O);
        saveButton.setMnemonic(KeyEvent.VK_S);
        closeButton.setMnemonic(KeyEvent.VK_X);
        hintButton.setMnemonic(KeyEvent.VK_Z);
        undoButton.setMnemonic(KeyEvent.VK_Y);

        timer = new Timer(1000, (ActionEvent a1) -> {
            int min, sec;
            time++;
            min = time / 60;
            sec = time % 60;
            jLabel1.setText("Time: " + min + ":" + sec);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newButton = new javax.swing.JButton();
        openButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        waste = new javax.swing.JPanel();
        wasteLabel = new javax.swing.JLabel();
        stock = new javax.swing.JPanel();
        stockLabel = new javax.swing.JLabel();
        hintButton = new javax.swing.JButton();
        undoButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        founcation1 = new javax.swing.JPanel();
        foundation3 = new javax.swing.JPanel();
        foundation4 = new javax.swing.JPanel();
        foundation2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableau7 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableau6 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableau1 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableau2 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableau5 = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableau3 = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        tableau4 = new javax.swing.JList<>();

        setBackground(new java.awt.Color(51, 204, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(600, 350));
        setMinimumSize(new java.awt.Dimension(600, 350));
        setPreferredSize(new java.awt.Dimension(630, 360));

        newButton.setText("New");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        openButton.setText("Open");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        wasteLabel.setText("jLabel2");

        javax.swing.GroupLayout wasteLayout = new javax.swing.GroupLayout(waste);
        waste.setLayout(wasteLayout);
        wasteLayout.setHorizontalGroup(
            wasteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wasteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wasteLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        wasteLayout.setVerticalGroup(
            wasteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wasteLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(wasteLabel)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stockMouseClicked(evt);
            }
        });

        stockLabel.setText("jLabel3");

        javax.swing.GroupLayout stockLayout = new javax.swing.GroupLayout(stock);
        stock.setLayout(stockLayout);
        stockLayout.setHorizontalGroup(
            stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stockLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        stockLayout.setVerticalGroup(
            stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(stockLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hintButton.setText("Hint");
        hintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintButtonActionPerformed(evt);
            }
        });

        undoButton.setText("Undo");
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout founcation1Layout = new javax.swing.GroupLayout(founcation1);
        founcation1.setLayout(founcation1Layout);
        founcation1Layout.setHorizontalGroup(
            founcation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        founcation1Layout.setVerticalGroup(
            founcation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        foundation3.setPreferredSize(new java.awt.Dimension(60, 0));

        javax.swing.GroupLayout foundation3Layout = new javax.swing.GroupLayout(foundation3);
        foundation3.setLayout(foundation3Layout);
        foundation3Layout.setHorizontalGroup(
            foundation3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        foundation3Layout.setVerticalGroup(
            foundation3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        foundation4.setPreferredSize(new java.awt.Dimension(60, 0));

        javax.swing.GroupLayout foundation4Layout = new javax.swing.GroupLayout(foundation4);
        foundation4.setLayout(foundation4Layout);
        foundation4Layout.setHorizontalGroup(
            foundation4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        foundation4Layout.setVerticalGroup(
            foundation4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout foundation2Layout = new javax.swing.GroupLayout(foundation2);
        foundation2.setLayout(foundation2Layout);
        foundation2Layout.setHorizontalGroup(
            foundation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        foundation2Layout.setVerticalGroup(
            foundation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setMinimumSize(new java.awt.Dimension(2, 2));

        jScrollPane1.setViewportView(tableau7);

        jScrollPane2.setViewportView(tableau6);

        jScrollPane3.setViewportView(tableau1);

        jScrollPane4.setViewportView(tableau2);

        jScrollPane5.setViewportView(tableau5);

        jScrollPane6.setViewportView(tableau3);

        jScrollPane7.setViewportView(tableau4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(openButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveButton)
                                .addGap(18, 18, 18)
                                .addComponent(hintButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(undoButton)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(closeButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(waste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(founcation1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(foundation2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(foundation3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(foundation4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(116, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newButton)
                        .addComponent(openButton)
                        .addComponent(saveButton)
                        .addComponent(hintButton)
                        .addComponent(undoButton))
                    .addComponent(closeButton)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(foundation2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(founcation1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(foundation3, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(foundation4, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(waste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        parent.rem(number);
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void hintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintButtonActionPerformed
        // Help next card
        if (active) {
        }
    }//GEN-LAST:event_hintButtonActionPerformed

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed
        board.goBack();
    }//GEN-LAST:event_undoButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        timer.start();
        jLabel1.setText("Time: 0:0");
        active = true;
        board.resetGame();

        final ListModel<Card> wasteModel = board.getListModel(Deck.WASTE, 0);
        Runnable updateWaste = () -> {
            wasteLabel.setText((wasteModel.getSize() > 0) ? wasteModel.getElementAt(wasteModel.getSize() - 1).getIconName() : "empty");
        };
        wasteModel.addListDataListener(new ListDataListener() {
            @Override
            public void intervalAdded(ListDataEvent e) {
                updateWaste.run();
            }

            @Override
            public void intervalRemoved(ListDataEvent e) {
                updateWaste.run();
            }

            @Override
            public void contentsChanged(ListDataEvent e) {
                updateWaste.run();
            }
        });
        updateWaste.run();

        final ListModel<Card> stockModel = board.getListModel(Deck.STOCK, 0);
        Runnable updateStock = () -> {
            stockLabel.setText((stockModel.getSize() > 0) ? stockModel.getElementAt(stockModel.getSize() - 1).getIconName() : "empty");
        };
        stockModel.addListDataListener(new ListDataListener() {
            @Override
            public void intervalAdded(ListDataEvent e) {
                updateStock.run();
            }

            @Override
            public void intervalRemoved(ListDataEvent e) {
                updateStock.run();
            }

            @Override
            public void contentsChanged(ListDataEvent e) {
                updateStock.run();
            }
        });
        updateStock.run();

        tableau1.setModel(board.getListModel(Deck.TABLEAU, 0));
        tableau2.setModel(board.getListModel(Deck.TABLEAU, 1));
        tableau3.setModel(board.getListModel(Deck.TABLEAU, 2));
        tableau4.setModel(board.getListModel(Deck.TABLEAU, 3));
        tableau5.setModel(board.getListModel(Deck.TABLEAU, 4));
        tableau6.setModel(board.getListModel(Deck.TABLEAU, 5));
        tableau7.setModel(board.getListModel(Deck.TABLEAU, 6));

        tableau1.setCellRenderer(new CardRenderer());
        tableau2.setCellRenderer(new CardRenderer());
        tableau3.setCellRenderer(new CardRenderer());
        tableau4.setCellRenderer(new CardRenderer());
        tableau5.setCellRenderer(new CardRenderer());
        tableau6.setCellRenderer(new CardRenderer());
        tableau7.setCellRenderer(new CardRenderer());

        // Konec testovaci sada
    }//GEN-LAST:event_newButtonActionPerformed

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        JFileChooser f = new JFileChooser();
        if (f.showOpenDialog(parent) == JFileChooser.APPROVE_OPTION) {
            jsolitaire.Board.deserialize(f.getSelectedFile()).apply(
                    x -> showMessageDialog(parent, x, "Chyba", JOptionPane.ERROR_MESSAGE),
                    x -> board = x);
        }
    }//GEN-LAST:event_openButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        JFileChooser f = new JFileChooser();
        if (f.showSaveDialog(parent) == JFileChooser.APPROVE_OPTION) {
            board.serialize(f.getSelectedFile())
                    .ifPresent(x -> showMessageDialog(parent, x, "Chyba", JOptionPane.ERROR_MESSAGE));
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void stockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockMouseClicked
        System.out.print(board.tryToMove(new Move(Deck.STOCK, 0, 0, Deck.WASTE, 0)));
        //when drag-and-dropping, if tryToMove == false, float the card back to its original position
    }//GEN-LAST:event_stockMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel founcation1;
    private javax.swing.JPanel foundation2;
    private javax.swing.JPanel foundation3;
    private javax.swing.JPanel foundation4;
    private javax.swing.JButton hintButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton newButton;
    private javax.swing.JButton openButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel stock;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JList<Card> tableau1;
    private javax.swing.JList<Card> tableau2;
    private javax.swing.JList<Card> tableau3;
    private javax.swing.JList<Card> tableau4;
    private javax.swing.JList<Card> tableau5;
    private javax.swing.JList<Card> tableau6;
    private javax.swing.JList<Card> tableau7;
    private javax.swing.JButton undoButton;
    private javax.swing.JPanel waste;
    private javax.swing.JLabel wasteLabel;
    // End of variables declaration//GEN-END:variables
}
